
 Declare @Idmaeedo int = #Idmaeedo#,
         @Tido Char(3) = '#Tido#'
 

SELECT TOP 1 IDMAEDDO,MAEEDO.TIDO,MAEEDO.NUDO,MAEEDO.ENDO,FEEMDO FROM MAEDDO  WITH ( NOLOCK ) INNER JOIN MAEEDO ON MAEDDO.IDMAEEDO = MAEEDO.IDMAEEDO  
WHERE MAEDDO.ARCHIRST='MAEEDO' AND MAEDDO.IDRST=@Idmaeedo

--SELECT TOP 1 IDMAEDDO,MAEEDO.TIDO,MAEEDO.NUDO,MAEEDO.ENDO,FEEMDO FROM MAEDDO  WITH ( NOLOCK ) INNER JOIN MAEEDO ON MAEDDO.IDMAEEDO = MAEEDO.IDMAEEDO  
--WHERE MAEDDO.ARCHIRST='MAEDDO' AND MAEDDO.IDRST=@Idmaeedo

If @Tido Not In ('COV','NVV','OCC','OCI') 
BEGIN

       SELECT TOP 1 IDMAEDPCD,TIDP,NUDP,ENDP,FEEMDP 
       FROM MAEDPCD  WITH ( NOLOCK ) 
        INNER JOIN MAEDPCE ON MAEDPCD.IDMAEDPCE = MAEDPCE.IDMAEDPCE  
        WHERE MAEDPCD.ARCHIRST='MAEEDO' AND MAEDPCD.IDRST=@Idmaeedo

       SELECT TOP 1 IDCOMPRD1,NUMECOM,FECHCOM 
       FROM CCOMPRD1  WITH ( NOLOCK ) 
        INNER JOIN CCOMPRD ON CCOMPRD1.IDCOMPRD = CCOMPRD.IDCOMPRD 
        INNER JOIN CCOMPRE ON CCOMPRD.IDCOMPRE = CCOMPRE.IDCOMPRE  WHERE CCOMPRD1.ARCHIRST='MAEEDO' AND CCOMPRD1.IDRST=@Idmaeedo

       SELECT TOP 1 IDCARTOLD,NUCAR,CTACTECAR 
       FROM CCARTOLD  WITH ( NOLOCK ) 
        INNER JOIN CCARTOLE ON CCARTOLD.IDCARTOLE = CCARTOLE.IDCARTOLE  
        WHERE CCARTOLD.ARCHIRST='MAEEDO' AND CCARTOLD.IDRST=@Idmaeedo

       SELECT TOP 1 IDDOCCOD,TIDO,NUDO,ENDO,FEEMDO 
       FROM CDOCCOD  WITH ( NOLOCK ) 
        INNER JOIN CDOCCOE ON CDOCCOE.IDDOCCOE = CDOCCOD.IDDOCCOE  
        WHERE CDOCCOD.ARCHIRST='MAEEDO' AND CDOCCOD.IDRST=@Idmaeedo


       SELECT TOP 1 IDPOTLCOM,POTL.NUMOT,POTL.NREG,POTL.CODIGO,POTL.GLOSA 
       FROM POTLCOM  WITH ( NOLOCK ) 
        INNER JOIN POTL ON POTLCOM.IDPOTL = POTL.IDPOTL INNER JOIN POTE ON POTL.IDPOTE = POTE.IDPOTE  
	    WHERE POTLCOM.ARCHIRST='MAEEDO' AND POTLCOM.IDRST=@Idmaeedo

       SELECT TOP 1 IDPDATFAD,PDATFAE.NUMDF,PDATFAE.FECHA 
       FROM PDATFAD  WITH ( NOLOCK ) 
        INNER JOIN PDATFAE ON PDATFAD.IDPDATFAE = PDATFAE.IDPDATFAE  
        WHERE PDATFAD.ARCHIRST='MAEEDO' AND PDATFAD.IDRST=@Idmaeedo
	   
       SELECT TOP 1 IDPDATTAD,PDATTAE.NUMDF,PDATTAE.FECHA 
       FROM PDATTAD  WITH ( NOLOCK ) 
        INNER JOIN PDATTAE ON PDATTAD.IDPDATTAE = PDATTAE.IDPDATTAE  
        WHERE PDATTAD.ARCHIRST='MAEEDO' AND PDATTAD.IDRST=@Idmaeedo

       SELECT TOP 1 * 
       FROM PTICKET WITH ( NOLOCK )  
        WHERE ARCHIRST='MAEEDO' AND IDRST=@Idmaeedo

       SELECT TOP 1 * 
       FROM PODCD WITH ( NOLOCK )  
        WHERE ARCHIRST='MAEEDO' AND IDRST=@Idmaeedo
 
       SELECT TOP 1 * 
       FROM MAEDCR WITH ( NOLOCK )  
        WHERE IDMAEEDO=@Idmaeedo

       SELECT TOP 1 IDMAEDPCD,TIDP,NUDP,ENDP,FEEMDP 
       FROM MAEDPCD  WITH ( NOLOCK ) INNER JOIN MAEDPCE ON MAEDPCD.IDMAEDPCE = MAEDPCE.IDMAEDPCE  
        WHERE MAEDPCD.ARCHIRST='MAEDDO' AND MAEDPCD.IDRST=@Idmaeedo

       SELECT TOP 1 IDCOMPRD1,NUMECOM,FECHCOM 
       FROM CCOMPRD1 WITH ( NOLOCK ) 
        INNER JOIN CCOMPRD ON CCOMPRD1.IDCOMPRD = CCOMPRD.IDCOMPRD INNER JOIN CCOMPRE ON 
        CCOMPRD.IDCOMPRE = CCOMPRE.IDCOMPRE  WHERE CCOMPRD1.ARCHIRST='MAEDDO' AND CCOMPRD1.IDRST=@Idmaeedo

       SELECT TOP 1 IDCARTOLD,NUCAR,CTACTECAR 
       FROM CCARTOLD  WITH ( NOLOCK ) INNER JOIN CCARTOLE ON CCARTOLD.IDCARTOLE = CCARTOLE.IDCARTOLE  
        WHERE CCARTOLD.ARCHIRST='MAEDDO' AND CCARTOLD.IDRST=@Idmaeedo

       SELECT TOP 1 IDDOCCOD,TIDO,NUDO,ENDO,FEEMDO 
       FROM CDOCCOD  WITH ( NOLOCK ) 
        INNER JOIN CDOCCOE ON CDOCCOE.IDDOCCOE = CDOCCOD.IDDOCCOE  
        WHERE CDOCCOD.ARCHIRST='MAEDDO' AND CDOCCOD.IDRST=@Idmaeedo

       SELECT TOP 1 IDPOTLCOM,POTL.NUMOT,POTL.NREG,POTL.CODIGO,POTL.GLOSA 
       FROM POTLCOM  WITH ( NOLOCK ) 
        INNER JOIN POTL ON POTLCOM.IDPOTL = POTL.IDPOTL INNER JOIN POTE ON POTL.IDPOTE = POTE.IDPOTE  
	    WHERE POTLCOM.ARCHIRST='MAEDDO' AND POTLCOM.IDRST=@Idmaeedo

       SELECT TOP 1 IDPDATFAD,PDATFAE.NUMDF,PDATFAE.FECHA 
       FROM PDATFAD  WITH ( NOLOCK ) 
        INNER JOIN PDATFAE ON PDATFAD.IDPDATFAE = PDATFAE.IDPDATFAE  WHERE PDATFAD.ARCHIRST='MAEDDO' AND PDATFAD.IDRST=@Idmaeedo
      
       SELECT TOP 1 IDPDATTAD,PDATTAE.NUMDF,PDATTAE.FECHA 
       FROM PDATTAD  WITH ( NOLOCK ) 
        INNER JOIN PDATTAE ON PDATTAD.IDPDATTAE = PDATTAE.IDPDATTAE  WHERE PDATTAD.ARCHIRST='MAEDDO' AND PDATTAD.IDRST=@Idmaeedo

       SELECT TOP 1 * 
       FROM PTICKET WITH ( NOLOCK )  
        WHERE ARCHIRST='MAEDDO' AND IDRST=@Idmaeedo

       SELECT TOP 1 * 
       FROM PODCD WITH ( NOLOCK )  
        WHERE ARCHIRST='MAEDDO' AND IDRST=@Idmaeedo

       SELECT TOP 1 * 
       FROM MAEDCR 
        WITH ( NOLOCK )  WHERE IDDDODCR=@Idmaeedo
End

--SELECT FTOPEELIM FROM CONFIEST WITH (NOLOCK) WHERE EMPRESA='01' AND MODALIDAD='  ' 
--SELECT TOP 1 TIDO FROM MAEDDO WITH ( NOLOCK )  WHERE EMPRESA='01' AND ENDOPA='1            ' AND TIDOPA='COV' AND NUDOPA='0000009215'

-- CONSULTA PARA SABER DATOS DE LA CONFIGURACION DEL SISTEMA, METODO DE COSTEO PPP EN CASO DE 
-- CRITERIOS COMPLEMENTARIO EN CASO DE ACTUALIZACION DE PPP
--SELECT TOP 1 DOCINTPPP,METODOPPP,EXCLUGRI,GRPAFEPPP,TRANAFEPPP FROM CONFIGP WITH ( NOLOCK )  WHERE EMPRESA='01'