'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Recurso_ImpDoc
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WebService_BakApp.Recurso_ImpDoc", GetType(Recurso_ImpDoc).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &lt;TED version=&quot;1.0&quot;&gt;&lt;DD&gt;&lt;RE&gt;#Re#&lt;/RE&gt;&lt;TD&gt;#TipoDTE#&lt;/TD&gt;&lt;F&gt;#Folio#&lt;/F&gt;&lt;FE&gt;#FchEmis#&lt;/FE&gt;&lt;RR&gt;#RUTRecep#&lt;/RR&gt;&lt;RSR&gt;#RznSocRecep#&lt;/RSR&gt;&lt;MNT&gt;#Mnt#&lt;/MNT&gt;&lt;IT1&gt;#It1#&lt;/IT1&gt;&lt;CAF version=&quot;1.0&quot;&gt;&lt;DA&gt;&lt;RE&gt;#Re#&lt;/RE&gt;&lt;RS&gt;#Rs#&lt;/RS&gt;&lt;TD&gt;#TipoDTE#&lt;/TD&gt;&lt;RNG&gt;&lt;D&gt;#Rng_d#&lt;/D&gt;&lt;H&gt;#Rng_h#&lt;/H&gt;&lt;/RNG&gt;&lt;FA&gt;#Fa#&lt;/FA&gt;&lt;RSAPK&gt;&lt;M&gt;#Rsapk_m#&lt;/M&gt;&lt;E&gt;#Rsapk_e#&lt;/E&gt;&lt;/RSAPK&gt;&lt;IDK&gt;#Idk#&lt;/IDK&gt;&lt;/DA&gt;&lt;FRMA#Frma#&lt;/FRMA&gt;&lt;/CAF&gt;&lt;TSTED&gt;#Tsted#&lt;/TSTED&gt;&lt;/DD&gt;&lt;FRMT algoritmo=&quot;SHA1withRSA&quot;&gt;&lt;/FRMT&gt;&lt;/TED&gt;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Genera_Timbre_Electronico_DTE_RdBk() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Genera_Timbre_Electronico_DTE_RdBk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Declare @Idmaeedo As int
        '''
        '''Set @Idmaeedo = #Idmaeedo#
        '''
        '''--UPDATE MAEEDO SET RUTCONTACT = &apos;13239873&apos; WHERE IDMAEEDO = @Idmaeedo
        '''
        '''SELECT 
        '''       -- MAEEDO 
        '''       Edo.IDMAEEDO, Edo.EMPRESA, Edo.TIDO, Edo.NUDO, Edo.TIDO+Edo.NUDO As &apos;Bk_Tido_Nudo&apos;, Edo.ENDO, Edo.SUENDO, Edo.ENDOFI, Edo.TIGEDO, Edo.SUDO,Sucedo.NOKOSU As &apos;NOMSUDO&apos;,
        '''	   Edo.LUVTDO, Edo.FEEMDO, Edo.KOFUDO, Resp.NOKOFU As &apos;Resp_NOKOFU&apos;, Edo.ESDO, Edo.ESPGDO, 
        '''       Edo.CAPRCO, Edo.CAPRAD, Edo.CAPREX, Edo.CAPRNC, Edo.MEARDO, Edo.MODO, Edo.TI [resto de la cadena truncado]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property SQLQuery_Traer_Documento_Para_Imprimir() As String
            Get
                Return ResourceManager.GetString("SQLQuery_Traer_Documento_Para_Imprimir", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
